server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:h2:mem:mydb;NON_KEYWORDS=USER
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/master_ticket?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sgs1159
    password: vace1159~
    hikari:
      maximum-pool-size: 20
  jpa:
    defer-datasource-initialization: true # data.sql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql.init.mode: always # data.sql
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
